# Generated by Django 5.2 on 2025-04-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0002_healthcareprovider_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='email',
        ),
    ]
